const lightTheme = {
    text: '#363537',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    wordWrap: 'break-word',
    background: '#fff',
    backgroundColor: '#fff',
    backgroundClip: 'border-box',
    borderTop: '#3db03d',
    borderRadius: '.25rem',
    marginBottom : '.75rem',
    footerText : '#fff',
    navBrand : '#fff !important',
    titleColor : '#fff',
    switchBorderRadius : '10px',
    togglebackground : '#111913',
    toggleIcon : 'rgb(136, 190, 125)',
    cardName : '#224422',
    navTheme : '#224422 !important',
}


const darkTheme = {
    text: '#363537',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    wordWrap: 'break-word',
    background: '#111913',
    backgroundColor: '#111913',
    backgroundClip: 'border-box',
    borderTop: '#3db03d',
    borderRadius: '.25rem',
    marginBottom : '.75rem',
    footerText : 'rgb(136, 190, 125)',
    navBrand : 'rgb(136, 190, 125)',
    titleColor : 'rgb(136, 190, 125)',
    switchBorderRadius : '10px',
    togglebackground : '#fff',
    toggleIcon : '#111913',
    cardName : '#1e7e34',
    navTheme: '#000000 !important',
}

export {lightTheme, darkTheme};
